name: 'GitHub API confine'
description:
  'This action can be used to obtain the remaining Github API quota and act
  accordingly.'
author: 'Matthias Zepper'

# Define your inputs here.
inputs:
  actionToTake:
    description:
      'Action to take if the API limit is underrun: Sweep (fail) or sleep (wait
      for quota renewal).'
    required: false
    default: 'sweep'
  threshold:
    description: 'API request threshold: Can be given as fraction (0.2 ; 20%) or absolute number (50)'
    required: false
    default: '10%'
  resource:
    description:
      'Github API quota to use for the action: One of "core", "search",
      "graphql", "integration_manifest" or "code_scanning_upload"'
    required: false
    default: 'core'
  token:
    description: 'Github API token to use for the action.'
    required: false
    default: ${{ github.token }}

# Define your outputs here.
outputs:
  remaining:
    description: 'Currently remaining requests for the specified quota.'

runs:
  using: node20
  main: dist/index.js
