name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action (sweep)
        id: sweep-test
        uses: ./
        with:
          actionToTake: 'sweep'
          lowerBound: 50
          debug: true

      - name: Print Output (sweep)
        id: output-sweep
        run: echo "${{ steps.sweep-test.outputs.remaining }}"

      - name: Test Local Action
        id: sleep-test
        uses: ./
        with:
          actionToTake: 'sleep'
          lowerBound: 1500
          debug: true

      - name: Print Output (sleep)
        id: output-sleep
        run: echo "${{ steps.sleep-test.outputs.remaining }}"
